@auth = JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6InR0dCIsImV4cCI6MTUzNzE5Njk5NCwiZW1haWwiOiIifQ.qHyL6C2-7IM7BN4VqGWYC7zfHgEo3FOp_PsiU_iUNu4
@baseUrl = http://localhost:8000/api-v0/


POST {{baseUrl}}api-token-auth/ HTTP/1.1
Content-Type: application/json

{
	"username": "ttt" ,
	"password": "apple123"
}


###

# register User
POST {{baseUrl}}users/ HTTP/1.1
Content-Type: application/json

{
    "username": "ttt",
    "password": "apple123",
    "password_again": "apple123",
    "location": {
        "address": "a simpel location",
        "lat": 123,
        "lng": 123.2
    },
    "tel": 12333
}

###

POST {{baseUrl}}msg/ HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
    # id of the parent message 
    "parentMsg":"",
    "msg":"sss"
}


###
# Finish the selected bid 
GET {{baseUrl}}posts/1/finish/ HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}


###
# Rate a bid 
POST  {{baseUrl}}posts/1/rate/ HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
    "rate" : "5"
}

# Bid actions: 
###
# Bidder rate a post 
POST  {{baseUrl}}bids/1/rate/ HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
    "rate" : "5"
}


# Event actions"
###
# create a post of sub event 
POST  {{baseUrl}}events/1/post/ HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
    
}