POST http://localhost:8000/api-v0/api-token-auth/ HTTP/1.1
Content-Type: application/json

{
	"username": "tecty" ,
	"password": "password"
}


###

POST http://localhost:8000/api-v0/msg/ HTTP/1.1
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlY3R5IiwiZXhwIjoxNTM2OTQxNzQwLCJlbWFpbCI6IiJ9.kv5rauKSS1xxQmxFgYdZB6VWa3gMFt5IymKekOKQpHU

{
    # id of the parent message 
    "parentMsg":"7",
    "msg":"sss"
}
