version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AnApple_123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions

  backend:
    build: .
    restart: always
    ports: 
      - "8000:8000"
    volumes: 
      - .:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
