version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AnApple_123
    volumes: 
      - partyWhipMysql:/var/lib/mysql

  myAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8081:80
    volumes:
     - /sessions

  backend:
    build: .
    restart: always
    ports: 
      - "8000:8000"
    volumes: 
      - .:/usr/src/app/
    command: 
    depends_on:
      - db

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
volumes: 
  partyWhipMysql: