#!/bin/bash


# update the prerequiste
pip install -r requirements.txt > /dev/null

echo "Create New Databsae"
./manage.py migrate >/dev/null

# echo "Import Basic Data"
# ScriptDependency/import_data.sh &

# echo "Create Super User"
# ./manage.py createsuperuser

echo "running the server"
./manage.py runserver
