#!/bin/bash


# update the prerequiste
pip install -r requirements.txt > /dev/null

echo "Migrate the Database"
./manage.py migrate >/dev/null

echo "Running the Server"
./manage.py runserver 0.0.0.0:8000
