# Generated by Django 2.1 on 2018-08-20 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1024)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('msg', models.CharField(blank=True, max_length=1024)),
                ('evenTime', models.DateTimeField()),
                ('bidClossingTime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('peopleCount', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(max_length=255)),
                ('extraCriteria', models.ManyToManyField(to='whip.Criteria')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whip.Post'),
        ),
    ]
