# Generated by Django 2.1 on 2018-08-15 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('eventType', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('peopleCount', models.IntegerField()),
                ('ageProfolio', models.CharField(max_length=255)),
                ('kitchenType', models.CharField(max_length=255)),
                ('provideCookery', models.BooleanField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(max_length=255)),
                ('extraCriteria', models.ManyToManyField(to='whip.Criteria')),
                ('renovaters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whip.Post')),
            ],
        ),
    ]
