# Generated by Django 2.1 on 2018-09-20 12:08

from django.db import migrations
from itertools import chain
from django.contrib.auth.management import create_permissions
from django.apps.registry import apps as apps_alt


def add_groups(apps,schema_editor):
    # create all ContentTypes premission before this migration
    for app_config in apps_alt.get_app_configs():
        create_permissions(app_config)
        
    Group = apps.get_model('auth','Group')
    Permission = apps.get_model('auth','Permission')
    """
    dividing two groups of user here
    - Set it's name
    - Clearify it's premission
    """
    # bidder group 
    bidder = Group.objects.create(name = "Bidder")

    permission_list = \
    list(
        chain(
            Permission.objects.filter(codename__contains = "event"),
            Permission.objects.filter(codename__contains = "post"),
            Permission.objects.filter(codename__contains = "message")
        )
    )


    # print(Permission.objects.all())


    # CRUD of post Event Msg 
    bidder.permissions.set(permission_list)
    print(bidder.permissions)
    print(permission_list)
    # save the setting 
    bidder.save()
    print(bidder.permissions)

    # poster group 
    poster = Group.objects.create(name = "Poster")
    permission_list = list(
        chain(
            Permission.objects.filter(codename__contains = "bid"),
            Permission.objects.filter(codename__contains = "message")
        )
    )

    # CRUD of post Event Msg 
    poster.permissions.set(permission_list)
    print(poster.permissions)
    print(permission_list)
    # save the setting 
    poster.save()
    print(poster.permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('whip', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups)
    ]
