# Generated by Django 2.1 on 2018-08-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='evenTime',
            new_name='eventTime',
        ),
        migrations.AlterField(
            model_name='post',
            name='extraParameter',
            field=models.ManyToManyField(blank=True, related_name='extra_parameter', to='whip.Parameter'),
        ),
    ]
