# Generated by Django 2.1 on 2018-09-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whip', '0002_auto_20180914_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posterReceivedPoints',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
