# Generated by Django 2.1 on 2018-09-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whip', '0003_auto_20180911_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whip.Message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whip.Message'),
        ),
    ]
