# Generated by Django 2.1 on 2018-09-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whip', '0003_auto_20180914_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='msg',
        ),
    ]
