# Generated by Django 2.1 on 2018-09-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whip', '0005_auto_20180912_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bidClossingTime',
            new_name='bidClosingTime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bidClossingTime',
            new_name='bidClosingTime',
        ),
    ]
