# Generated by Django 2.1 on 2018-09-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whip', '0006_auto_20180912_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='address',
        ),
    ]
